apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240 - 192.168.1.254  # IP Range of addresses to assing.
  # Or use CIDR notation meaning the same as above.
  # - 192.168.1.240/28
---
apiVersion: metallb.io/v1beta1
kind: labels
metadata:
  name: metallb-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool